version: '3.6'
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: guacdb
      MYSQL_USER: guacuser
      MYSQL_PASSWORD: guacuserpw
    volumes:
      - ${PWD}/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
  guacd:
    image: guacamole/guacd
    depends_on:
    - mariadb
    restart: unless-stopped
  guacamole:
    image: guacamole/guacamole
    depends_on:
    - guacd
    ports:
    - '8080:8080'
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mariadb
      MYSQL_DATABASE: guacdb
      MYSQL_USER: guacuser
      MYSQL_PASSWORD: guacuserpw
    restart: unless-stopped
volumes:
  mysql_data:
